apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-app
  template:
    metadata:
      labels:
        app: event-app
    spec:
      containers:
        - name: event-app
          image: kevinabraham28/event-app:latest